# Generated by Django 6.0.1 on 2026-01-06 20:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrondissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('area_km2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='BikeStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('total_docks', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrondissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='analytics.arrondissement')),
            ],
            options={
                'ordering': ['station_id'],
            },
        ),
        migrations.CreateModel(
            name='DailyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_trips', models.IntegerField(default=0)),
                ('total_duration_minutes', models.IntegerField(default=0)),
                ('average_duration_minutes', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('average_utilization', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('peak_hour', models.IntegerField(blank=True, null=True)),
                ('arrondissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='analytics.arrondissement')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='analytics.bikestation')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='analytics_d_date_8ce489_idx'), models.Index(fields=['arrondissement', '-date'], name='analytics_d_arrondi_dc0490_idx'), models.Index(fields=['station', '-date'], name='analytics_d_station_6fe85e_idx')],
                'unique_together': {('date', 'arrondissement', 'station')},
            },
        ),
        migrations.CreateModel(
            name='StationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('available_bikes', models.IntegerField()),
                ('available_docks', models.IntegerField()),
                ('is_operational', models.BooleanField(default=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='analytics.bikestation')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='analytics_s_timesta_d030e8_idx'), models.Index(fields=['station', '-timestamp'], name='analytics_s_station_9ddfb3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=100, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('user_type', models.CharField(choices=[('subscriber', 'Subscriber'), ('customer', 'Customer')], max_length=50)),
                ('end_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_ended', to='analytics.bikestation')),
                ('start_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_started', to='analytics.bikestation')),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['-start_time'], name='analytics_t_start_t_9e80d4_idx'), models.Index(fields=['start_station', '-start_time'], name='analytics_t_start_s_edccd9_idx'), models.Index(fields=['end_station', '-start_time'], name='analytics_t_end_sta_b45042_idx')],
            },
        ),
    ]
