# Generated by Django 5.0.1 on 2026-01-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikestation',
            name='profile',
            field=models.CharField(choices=[('commuter_source', 'Commuter Source'), ('commuter_sink', 'Commuter Sink'), ('balanced_hub', 'Balanced Hub'), ('ghost_station', 'Ghost Station'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='dailyanalytics',
            name='average_hourly_delta',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average hourly change in bike count (V_h)', max_digits=8),
        ),
        migrations.AddField(
            model_name='dailyanalytics',
            name='is_ghost',
            field=models.BooleanField(default=False, help_text='Low entropy + low turnover'),
        ),
        migrations.AddField(
            model_name='dailyanalytics',
            name='is_sink',
            field=models.BooleanField(default=False, help_text='Net negative flux (demands bikes)'),
        ),
        migrations.AddField(
            model_name='dailyanalytics',
            name='is_source',
            field=models.BooleanField(default=False, help_text='Net positive flux (supplies bikes)'),
        ),
        migrations.AddField(
            model_name='dailyanalytics',
            name='net_flux',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of all deltas (Source > 0, Sink < 0)', max_digits=8),
        ),
        migrations.AddField(
            model_name='dailyanalytics',
            name='persistence_at_empty',
            field=models.IntegerField(default=0, help_text='Hours at 0% capacity'),
        ),
        migrations.AddField(
            model_name='dailyanalytics',
            name='persistence_at_full',
            field=models.IntegerField(default=0, help_text='Hours at 100% capacity'),
        ),
        migrations.AddField(
            model_name='dailyanalytics',
            name='shannon_entropy',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Station predictability (0-8)', max_digits=5),
        ),
        migrations.AddIndex(
            model_name='dailyanalytics',
            index=models.Index(fields=['is_source'], name='analytics_d_is_sour_1e4f56_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyanalytics',
            index=models.Index(fields=['is_sink'], name='analytics_d_is_sink_a0fb2b_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyanalytics',
            index=models.Index(fields=['is_ghost'], name='analytics_d_is_ghos_e84629_idx'),
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
