# Generated by Django 5.0.1 on 2026-01-12 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_remove_trip_end_station_remove_trip_start_station_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('area_km2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.RemoveField(
            model_name='bikestation',
            name='arrondissement',
        ),
        migrations.RemoveIndex(
            model_name='dailyanalytics',
            name='analytics_d_arrondi_dc0490_idx',
        ),
        migrations.AlterUniqueTogether(
            name='dailyanalytics',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bikestation',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='analytics.commune'),
        ),
        migrations.AddField(
            model_name='dailyanalytics',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='analytics.commune'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyanalytics',
            unique_together={('date', 'commune', 'station')},
        ),
        migrations.AddIndex(
            model_name='dailyanalytics',
            index=models.Index(fields=['commune', '-date'], name='analytics_d_commune_92db3d_idx'),
        ),
        migrations.RemoveField(
            model_name='dailyanalytics',
            name='arrondissement',
        ),
        migrations.DeleteModel(
            name='Arrondissement',
        ),
    ]
