# Generated by Django 5.0.1 on 2026-01-12 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_commune_remove_bikestation_arrondissement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikestation',
            name='coordinates',
            field=models.JSONField(blank=True, help_text='Geographic coordinates as GeoJSON Point', null=True),
        ),
        migrations.CreateModel(
            name='WeeklyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(help_text='Monday of the week')),
                ('week_end_date', models.DateField(help_text='Sunday of the week')),
                ('total_trips', models.IntegerField(default=0, help_text='Total trips for the week')),
                ('total_duration_minutes', models.IntegerField(default=0, help_text='Sum of all trip durations')),
                ('average_duration_minutes', models.DecimalField(decimal_places=2, default=0, help_text='Average trip duration', max_digits=6)),
                ('average_utilization', models.DecimalField(decimal_places=2, default=0, help_text='Average bike utilization rate', max_digits=5)),
                ('peak_day', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Busiest day of week (0=Monday, 6=Sunday)', null=True)),
                ('peak_hour', models.IntegerField(blank=True, help_text='Most busy hour (0-23)', null=True)),
                ('average_hourly_delta', models.DecimalField(decimal_places=2, default=0, help_text='Average hourly change in bike count', max_digits=8)),
                ('shannon_entropy', models.DecimalField(decimal_places=2, default=0, help_text='Average entropy for the week (0-8)', max_digits=5)),
                ('net_flux', models.DecimalField(decimal_places=2, default=0, help_text='Weekly sum of all deltas', max_digits=8)),
                ('persistence_at_full', models.IntegerField(default=0, help_text='Total hours at 100% capacity')),
                ('persistence_at_empty', models.IntegerField(default=0, help_text='Total hours at 0% capacity')),
                ('is_source', models.BooleanField(default=False, help_text='Net positive flux (supplies bikes)')),
                ('is_sink', models.BooleanField(default=False, help_text='Net negative flux (demands bikes)')),
                ('is_ghost', models.BooleanField(default=False, help_text='Low entropy + low turnover')),
                ('operational_hours', models.IntegerField(default=0, help_text='Total hours operational')),
                ('maintenance_incidents', models.IntegerField(default=0, help_text='Number of maintenance events')),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_analytics', to='analytics.commune')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_analytics', to='analytics.bikestation')),
            ],
            options={
                'ordering': ['-week_start_date'],
                'indexes': [models.Index(fields=['-week_start_date'], name='analytics_w_week_st_8483eb_idx'), models.Index(fields=['commune', '-week_start_date'], name='analytics_w_commune_1964eb_idx'), models.Index(fields=['station', '-week_start_date'], name='analytics_w_station_16e8a3_idx'), models.Index(fields=['is_source'], name='analytics_w_is_sour_6f483a_idx'), models.Index(fields=['is_sink'], name='analytics_w_is_sink_3cb36c_idx'), models.Index(fields=['is_ghost'], name='analytics_w_is_ghos_c68d65_idx')],
                'unique_together': {('week_start_date', 'commune', 'station')},
            },
        ),
    ]
