# Generated by Django 5.0.1 on 2026-01-20 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_bikestation_fields_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bikestation',
            options={'ordering': ['stationcode']},
        ),
        migrations.RemoveField(
            model_name='dailyanalytics',
            name='average_duration_minutes',
        ),
        migrations.RemoveField(
            model_name='dailyanalytics',
            name='total_duration_minutes',
        ),
        migrations.RemoveField(
            model_name='dailyanalytics',
            name='total_trips',
        ),
        migrations.RemoveField(
            model_name='weeklyanalytics',
            name='average_duration_minutes',
        ),
        migrations.RemoveField(
            model_name='weeklyanalytics',
            name='total_duration_minutes',
        ),
        migrations.RemoveField(
            model_name='weeklyanalytics',
            name='total_trips',
        ),
        migrations.AlterField(
            model_name='bikestation',
            name='stationcode',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='HourlyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='Hour timestamp (rounded down)')),
                ('date', models.DateField(help_text='Date of the hour')),
                ('hour', models.IntegerField(help_text='Hour of day (0-23)')),
                ('average_utilization', models.DecimalField(decimal_places=2, default=0, help_text='Average bike utilization %', max_digits=5)),
                ('bikes_available_avg', models.IntegerField(default=0, help_text='Average bikes available')),
                ('docks_available_avg', models.IntegerField(default=0, help_text='Average docks available')),
                ('hourly_delta', models.DecimalField(decimal_places=2, default=0, help_text='Change in bikes from previous hour', max_digits=8)),
                ('data_points', models.IntegerField(default=0, help_text='Number of status records for this hour')),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hourly_analytics', to='analytics.commune')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hourly_analytics', to='analytics.bikestation')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='analytics_h_timesta_ed861d_idx'), models.Index(fields=['station', '-timestamp'], name='analytics_h_station_35deec_idx'), models.Index(fields=['commune', '-timestamp'], name='analytics_h_commune_90c121_idx'), models.Index(fields=['date', 'hour'], name='analytics_h_date_88715b_idx')],
                'unique_together': {('timestamp', 'commune'), ('timestamp', 'station')},
            },
        ),
    ]
